dist: trusty
sudo: required

language: node_js
node_js:
  - "10"
git:
  depth: false
  submodules: true

addons:
  sonarcloud:
    organization: "cdadt"
    token:
      secure: 905f5eba405b0bafc9adf9f2026d30a3943f2052 # encrypted value of your token
  apt:
    sources:
      - google-chrome
      - ng-common
    packages:
      - google-chrome-stable

cache:
  directories:
    - /home/travis/build/cdadt/glossaire/app/node_modules
    - /home/travis/build/cdadt/glossaire/api/node_modules

install:
  - cd /home/travis/build/cdadt/glossaire/app
  - npm install
  - git pull
  - cd /home/travis/build/cdadt/glossaire/api
  - npm install
  - git pull

script:
  - cd /home/travis/build/cdadt/glossaire/app
  - pwd
  - ls -al
  - npm run test
  - sonar-scanner
  - cd /home/travis/build/cdadt/glossaire/api
  - pwd
  - ls -al
  - npm run test
  - sonar-scanner
