dist: trusty
sudo: required

git:
  depth: false
  submodules: true

addons:
  sonarcloud:
    organization: "cdadt"
    token:
      secure: 905f5eba405b0bafc9adf9f2026d30a3943f2052 # encrypted value of your token

matrix:
  include:
    - language: node_js
      node_js:
        - "10"
  
      apt:
      sources:
        - google-chrome
        - ng-common
      packages:
        - google-chrome-stable
  
      cache:
        directories:
          - /home/travis/build/cdadt/glossaire/app/node_modules
          
      install:
        - cd /home/travis/build/cdadt/glossaire/app
        - npm install
  
      script:
        - cd /home/travis/build/cdadt/glossaire/app
        - pwd
        - npm run test
        - sonar-scanner
  
    - language: node_js
      node_js:
        - "10"
  
      cache:
        directories:
          - /home/travis/build/cdadt/glossaire/api/node_modules
  
      install:
        - cd /home/travis/build/cdadt/glossaire/api
        - npm install
  
      script:
        - cd /home/travis/build/cdadt/glossaire/api
        - pwd
        - npm run test
        - sonar-scanner
