dist: trusty
sudo: false

git:
  depth: false
  submodules: true

addons:
  sonarcloud:
    organization: "cdadt"
    token:
      secure: 905f5eba405b0bafc9adf9f2026d30a3943f2052 # encrypted value of your token

matrix:
  include:
  language: node_js
    node_js:
      - "10"

    apt:
    sources:
      - google-chrome
      - ng-common
    packages:
      - google-chrome-stable
      
    cache:
      directories:
        - $HOME/app/node_modules

    install:
      - npm install

    script:
      - npm run test
      - sonar-scanner

  - language: node_js
    node_js:
      - "10"

    cache:
      directories:
        - $HOME/api/node_modules

    install:
      - npm install

    script:
      - npm run test
      - sonar-scanner
